### PR TITLE
Issue #180 resolved

### PR DESCRIPTION
**Pull request by Shubham-Zone**
## Problem / Issue No.
- Issue #180 : Implement UI Changes for Seamless Scrolling of Top Elements on Programs Screen

## Describe Problem / Root Cause
- The screen contained multiple nested ScrollViews, causing conflicting scroll behaviors. This made it difficult for the user to scroll through the entire screen smoothly, leading to a poor user experience. The primary ScrollView was not functioning correctly due to interference from the nested scrollable widgets.

## Solution Proposed
- The solution involved setting the `physics` property of the nested ListView widgets to `NeverScrollableScrollPhysics()`. This ensures that these ListViews do not handle any scroll events, allowing the primary ScrollView to manage scrolling for the entire screen. This change prevents conflicts between the scrollable widgets and ensures a smooth scrolling experience for the user.

### Code Changes:
```dart
ListView(
  physics: NeverScrollableScrollPhysics(),
  //...
)
```

## Additional Information
- This solution was applied to all nested ListView widgets within the screen. By making these ListViews non-scrollable, the primary ScrollView can properly handle all scrolling, resulting in a smoother user experience.

## Video of changes

https://github.com/andoriyaprashant/OpSo/assets/154971588/d18b7de7-abb3-4406-9972-15ba0a2d9169

### CODE REVIEW

**Comment by Shubham-Zone** [comment]
@andoriyaprashant i have created a PR. this issue is fixed please merge and close the issue

**Comment by andoriyaprashant** [comment]
@Shubham-Zone Remove unnecessary code files

**Comment by Shubham-Zone** [comment]
@andoriyaprashant i have removed all the unnecessary code files

**Comment by RishavKumarSinha** [comment]
@andoriyaprashant , the changes done in this pull request causes the projects in the Summer of Bitcoin and GSSoC Page to be unscrollable as 
`  physics: NeverScrollableScrollPhysics(),`
is applied to the widget _buildProjectList thus effectively stopping the users from accessing any more projects than shown on the front screen.

**Comment by Shubham-Zone** [comment]
@RishavKumarSinha this is the issue of responsiveness of the app ... you can add an issue related to the responsiveness

**Pull request merged**
