### PR TITLE
back arrow and title updated

### PR DESCRIPTION
**Pull request by WednesdaySP**
## Problem / Issue No.
BUG: title alignment issue in the appbar #346

## Describe Problem / Root Cause
the titles of all the pages are not aligned in center and also for moving back the default back arrow is used rather a customized ios arrow should be used to enhance the UI of application.

## Solution proposed
Changed the back arrow from default icon to ios icon and centered the title in appbar

## Additional Information
- Relevant information regarding the solution.

## Screenshots
- Original Screenshot (Problem/Issue)
- Updated Screenshot (Fixes/Solution)

https://github.com/user-attachments/assets/645208a9-bba1-4bbc-b008-c214dd68f6c5

### CODE REVIEW

**Comment by WednesdaySP** [comment]
@andoriyaprashant all the unwanted files are removed, now you can merge.

**Comment by WednesdaySP** [comment]
@andoriyaprashant  can you review this pr and merge it, as it has been closed by the bot without merging

**Comment by WednesdaySP** [comment]
@andoriyaprashant  hii, it has been so long since you reviewed this pr and now it has been closed automatically, please review it asap, and merge this pr with all the required labels, I'm GSSoC -ext contributor, and it's necessary for me to get this pr merged before 31st Oct. Please have a look into it.

**Comment by andoriyaprashant** [comment]
Sorry for the delay @WednesdaySP 
Thanks for contributing

**Pull request merged**
