### PR TITLE
GSSOC project list 2021 - 2024

### PR DESCRIPTION
**Pull request by ShashankDeepak**
## Context
This pull request is regarding issue #28 

## Description
This PR provides a list of almost all GSSOC projects currently available on the website from the year 2021 - 2024. They are all in the JSON file format. 

## Codebase changes
A total of 4 files have been included in assets\projects\gssoc which contain JSON files for the project in years 2021,2022,2023 and 2024 respectively.

### CODE REVIEW

**Comment by andoriyaprashant** [comment]
Good work @ShashankDeepak , but I want these projects to be displayed in the app when we click on the 'GirlScript' program's projects. Please ensure these projects are showcased within that program

**Comment by ShashankDeepak** [comment]
Ok, I will do it.

> Good work @ShashankDeepak , but I want these projects to be displayed in the app when we click on the 'GirlScript' program's projects. Please ensure these projects are showcased within that program

Ok I will do it

**Comment by andoriyaprashant** [comment]
> > Good work @ShashankDeepak , but I want these projects to be displayed in the app when we click on the 'GirlScript' program's projects. Please ensure these projects are showcased within that program
> 
> Ok I will do it

and I want this project's list to be displayed properly with the app UI
gssoc page opso

**Comment by ShashankDeepak** [comment]
Yes @andoriyaprashant I will make sure the UI will be the same and responsive.

**Comment by ShashankDeepak** [comment]
@andoriyaprashant What is the use of back arrow at the bottom?

**Comment by andoriyaprashant** [comment]
> @andoriyaprashant What is the use of back arrow at the bottom?

I have only added a demo UI to this app so far, and if you wish, you can also make changes to the UI. If we find it suitable after reviewing, we'll incorporate them. However, we want the data of projects and organizations to be displayed well for the user

**Comment by ShashankDeepak** [comment]
https://github.com/andoriyaprashant/OpSo/assets/92669664/8e0aedcc-3e12-43f8-844b-557645d3f91e

@andoriyaprashant 
This is what the GSSOC page looks like as of now, if you find any issues please inform. Otherwise, you can merge the PR.

**Comment by andoriyaprashant** [comment]
@ShashankDeepak  Good one! We would like projects and organizations from other programs to be displayed in the same way within this app. If you wish, you can also create issue and work on them

**Pull request merged**
