### PR TITLE
Implemented Project Features for GSoC Page

### PR DESCRIPTION
**Pull request by Saumya-28**
#117 

## Implemented Project Features for GSoC Page

- Added additional information about GSoC Projects(Blog url, Category, Contact Mail)
- UI Enhancements

### CODE REVIEW

**Comment by yagnik2411** [comment]
@Saumya-28 we need like gssoc so you should add 2 clickable widgets that redirect to email and blog. and category added like technology.

**Comment by Saumya-28** [comment]
I have implemented your feedback. Please Check once.

**Comment by yagnik2411** [comment]
can you share ss

**Comment by Saumya-28** [comment]
I have updated it in the comments above please check.

**Comment by yagnik2411** [comment]
@Saumya-28 awesome work

**Comment by Saumya-28** [comment]
Great! Thank you @yagnik2411 !

**Comment by yagnik2411** [comment]
@Saumya-28 we have some logic errors in this page
do you want to work it.i will make this level 2

**Comment by andoriyaprashant** [comment]
@Saumya-28 Please fix this Range error
Screenshot 2024-05-21 121044

**Comment by Saumya-28** [comment]
> @Saumya-28 we have some logic errors on this page do you want to work on it? i will make this PR to level2

Sure will work on it

**Comment by Saumya-28** [comment]
> @Saumya-28 Please fix this Range error Screenshot 2024-05-21 121044

Sure, will fix it.

**Comment by Saumya-28** [comment]
I have fixed the range error please check once @andoriyaprashant

**Pull request merged**
