### PR TITLE
Implemented chatbot feature for open source queries using Gemini

### PR DESCRIPTION
**Pull request by Saumya-28**
#192

### CODE REVIEW

**Comment by andoriyaprashant** [comment]
@Saumya-28 
I think you will need to work a bit more on adding this feature.

image

**Comment by Saumya-28** [comment]
@andoriyaprashant I would suggest you to add your own gemini api key for getting response from the chatbot as I have removed mine for security purpose.

**Comment by Saumya-28** [comment]
@andoriyaprashant please review the code and let me know

**Comment by Saumya-28** [comment]
@andoriyaprashant it would be helpful if you could let me know about the code.

**Comment by andoriyaprashant** [comment]
@Saumya-28 please resolve conflicts

**Comment by Saumya-28** [comment]
@andoriyaprashant I have resolved the merge conflict kindly review and let me know

**Pull request merged**
