### PR TITLE
Fixed the UI of GSoD screen

### PR DESCRIPTION
**Pull request by SumitPareek2401**
The user interface of Google Summer of Docs has been fixed as per our requirements.

Screenshots:
gsodS

### CODE REVIEW

**Comment by SumitPareek2401** [comment]
can you please elaborate on it? Should I need to fixed the scroll issue (like #86),

**Comment by andoriyaprashant** [comment]
> can you please elaborate on it? Should I need to fixed the scroll issue (like #86),

Fix the 2023 button so that it displays fully, similar to how it appears on the GirlScript Summer of Code screen
image

**Comment by SumitPareek2401** [comment]
@andoriyaprashant please check and review it.

**Comment by andoriyaprashant** [comment]
@SumitPareek2401 
image

I don't need any other changes on this screen. Just make the changes shown in this image and push them. Remove all other changes.

**Comment by andoriyaprashant** [comment]
> @SumitPareek2401 image
> 
> I don't need any other changes on this screen. Just make the changes shown in this image and push them. Remove all other changes.

@SumitPareek2401 you dont need to change gsod widget file (old and new ) just add this code

**Comment by SumitPareek2401** [comment]
So you want to change the google_season_of_docs_screen.dart screen. And which code do you want to have inserted in this file. (Left one or right one?)

> > @SumitPareek2401 image
> > I don't need any other changes on this screen. Just make the changes shown in this image and push them. Remove all other changes.
> 
> @SumitPareek2401 you dont need to change gsod widget file (old and new ) just add this code

**Comment by SumitPareek2401** [comment]
@andoriyaprashant please tell me.

**Comment by andoriyaprashant** [comment]
> google_season_of_docs_screen.dart screen

Make only the changes I mentioned in the google_season_of_docs_screen.dart screen @SumitPareek2401

**Comment by yagnik2411** [comment]
@SumitPareek2401  this is not look like gssoc screen

**Comment by SumitPareek2401** [comment]
@yagnik2411 I already asked about suggestions for UI in #79 to @andoriyaprashant. If you want any changes then I will do it.

**Pull request merged**
