### PR TITLE
Create project structure

### PR DESCRIPTION
**Pull request by banasmita24**
Issue: #383 
I have added a new file name "Project_Structure.md" as the project structure was too long and couldn't adjust in readme.md
Thank you:)

### CODE REVIEW

**Comment by andoriyaprashant** [comment]
@banasmita24 What about modals, program screen files etc?

**Comment by banasmita24** [comment]
@andoriyaprashant sorry i missed the ios and windows folder. Will modify!

**Comment by andoriyaprashant** [comment]
> @andoriyaprashant sorry i missed the lib and windows folder. Will modify!

Any updates? @banasmita24

**Comment by banasmita24** [comment]
@andoriyaprashant sorry for the delay. I have updated the `Project_Structure.md`. Please do check and let me know if I need to change something.
Thank you :)

**Comment by andoriyaprashant** [comment]
> @andoriyaprashant sorry for the delay. I have updated the `Project_Structure.md`. Please do check and let me know if I need to change something.
> 
> Thank you :)

Done @banasmita24 
Thanks for contributing 👍🏻

**Pull request merged**
