### PR TITLE
Linux Foundation page added

### PR DESCRIPTION
**Pull request by ShashankDeepak**
## Problem / Issue No.
- This PR is related to issue #89 

## Describe Problem / Root Cause
- There was no UI available for Linux Foundation page.

## Solution proposed
- Created a minimal UI page showing projects that are part of the Linux Foundation. Also implemented a search feature so that users can search for any project.

## Video

https://github.com/andoriyaprashant/OpSo/assets/92669664/5bdfca92-fdc2-4b89-b000-4f7d857d172c

### CODE REVIEW

**Comment by yagnik2411** [comment]
@ShashankDeepak you should update the ui according to the gsspc page

**Comment by ShashankDeepak** [comment]
> @ShashankDeepak you should update the ui according to the gsspc page

@yagnik2411 Creating this page similar to GSSoC page is not possible. It would help if you looked into the [Linux Foundation ](https://www.linuxfoundation.org/projects)website for projects, you will find the projects listed are not year-wise so making it year-wise just like GSSoC is not possible. You should also look into the JSON file containing the data content in both Gssoc and Linux Foundation JSON files are very different. 

Also, the issue is not Level 1 but level 2.

**Comment by yagnik2411** [comment]
@ShashankDeepak  PA @andoriyaprashant wants ui look like gssoc.

**Comment by andoriyaprashant** [comment]
@ShashankDeepak make some changes to this page's UI to match the demo UI shown. Specifically, make the borders of the containers rounded 
Demo ui LFX

**Comment by ShashankDeepak** [comment]
@andoriyaprashant The new UI looks like this 
image

**Comment by yagnik2411** [comment]
@andoriyaprashant review this then i merge it

**Pull request merged**
