### PR TITLE
Added bookmark icon for all programs and bookmark page.

### PR DESCRIPTION
**Pull request by Pra-kas**

### CODE REVIEW

**Comment by yagnik2411** [comment]
it would be best if you described the changes @Pra-kas

**Comment by Pra-kas** [comment]
Sir I have added bookmark icon in each program. I have added a bookmark section above About section. Also resolve overflow issues in About section.

**Comment by Pra-kas** [comment]
> @Pra-kas I tested the bookmark feature on the GSOD program. When I clicked on the bookmark option, it showed 'Bookmark added,' but when I checked in the bookmarks section, there was nothing there. Please fix this bug and also resolve the conflicts

Should I need to implement this in static manner? Or
We need user details so that we can track which user is bookmarked the program.To implement this we need to work on backend feature also sir.

**Comment by yagnik2411** [comment]
@Pra-kas we have a conflict in the bar. dart

also use SQLite or shred preference right now

**Comment by Pra-kas** [comment]
> @Pra-kas we have a conflict in the bar. dart
> 
> also use SQLite or shred preference right now

Ok sir

**Comment by yagnik2411** [comment]
@Pra-kas i will check in 1-2 day

**Comment by Pra-kas** [comment]
@yagnik2411  Sir i have resolved bookmark feature bug and also resolved conflicts.

[Screencast from 2024-05-16 19-15-10.webm](https://github.com/andoriyaprashant/OpSo/assets/103827847/97887554-a38e-43d1-946c-b1971eb75bbc)

**Comment by yagnik2411** [comment]
@Pra-kas we have a conflict on the homepage.dart
slove this and I check it and merge it

**Pull request merged**
